[tool.poetry]
name = "django ig"
version = "0.1.0"
description = ""
authors = ["Lainina <ledenes04@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
